### PR TITLE
feat: implement --cache-from

### PR DESCRIPTION
**Pull request by orisano**
I implemented --cache-from option.

#205

### CODE REVIEW

**Comment by orisano** [comment]
#205

this pr is currently not working... sorry

**Comment by orisano** [comment]
this pr is currently not working... sorry

**Comment by AkihiroSuda** [comment]
this one needs https://github.com/moby/buildkit/pull/777

**Comment by ChrisPenner** [comment]
Looks like the referenced issue has been merged into BuildKit; any new developments here? @AkihiroSuda @orisano

**Pull request closed without merging**
