### PR TITLE
git ignoring direnv files to support per folder vars like IMG_DISABLE_EMBEDDED_RUNC

### PR DESCRIPTION
**Pull request by frezbo**
Signed-off-by: Noel Georgi <18496730+frezbo@users.noreply.github.com>

### CODE REVIEW

**Comment by frezbo** [comment]
Hmm that would cause to whitelist files like `.dockerignore`, `.travis.yml`? What do you say?

**Comment by jessfraz** [comment]
Can you not make this part of your global gitignore?

**Comment by AkihiroSuda** [comment]
```
.??*
!.dockerignore
!.gitignore
!.travis.yml
```

But probably global gitignore is better

**Comment by frezbo** [comment]
Yup sure, https://github.com/genuinetools/img/pull/112#issuecomment-394156890 . Most of my projects use `direnv` , thought it might be a god option to push upstream

**Pull request merged**
