### PR TITLE
support specifying `# syntax =` 

### LINKED ISSUE #136: Fails to build with latest Buildkit features
@AkihiroSuda @jessfraz Vendor-ed in the latest buildkit and build img. Details below:

**Img Version**
```
img (aws:rean-gov-sd)(kc)$ img version
img:
 version     : v0.4.6
 git hash    : bcebacfc-dirty
 go version  : go1.10.3
 go compiler : gc
 platform    : linux/amd64
```
**Img  build details**
```
img (aws:rean-gov-sd)(kc)$ img build -t hello . 
Building docker.io/library/hello:latest
Setting up the rootfs... this may take a bit.
[+] Building 1.9s (2/2) FINISHED                                                                                                                      
 => local://context (.dockerignore)                                                                                                              0.6s
 => => transferring context: 02B                                                                                                                 0.0s
 => local://dockerfile (Dockerfile)                                                                                                              1.2s
 => => transferring dockerfile: 201B                                                                                                             0.0s
failed to solve: invalid frontend: gateway.v0
```
**Same build with docker with buildkit support enabled**
```
img (aws:rean-gov-sd)(kc)$ export DOCKER_BUILDKIT=1
```

```
img (aws:rean-gov-sd)(kc)$ docker build -t hello .
[+] Building 20.6s (9/9) FINISHED                                                                                                                     
 => local://dockerfile (Dockerfile)                                                                                                              0.7s
 => => transferring dockerfile: 207B                                                                                                             0.1s
 => local://context (.dockerignore)                                                                                                              0.8s
 => => transferring context: 02B                                                                                                                 0.1s
 => docker-image://docker.io/tonistiigi/dockerfile:runmount20180618                                                                              0.0s
 => => resolve docker.io/tonistiigi/dockerfile:runmount20180618                                                                                  0.0s
 => local://dockerfile (Dockerfile)                                                                                                              0.0s
 => local://context (.dockerignore)                                                                                                              0.0s
 => docker-image://docker.io/library/alpine@sha256:b87c896a6482300775868561df3701b71e90c582aa606706fb6f4ea7249e5fdc                              7.6s
 => => resolve docker.io/library/alpine@sha256:b87c896a6482300775868561df3701b71e90c582aa606706fb6f4ea7249e5fdc                                  0.0s
 => => sha256:b87c896a6482300775868561df3701b71e90c582aa606706fb6f4ea7249e5fdc 1.72kB / 1.72kB                                                   0.0s
 => => sha256:0873c923e00e0fd2ba78041bfb64a105e1ecb7678916d1f7776311e45bf5634b 528B / 528B                                                       0.0s
 => => sha256:11cd0b38bc3ceb958ffb2f9bd70be3fb317ce7d255c8a4c3f4af30e298aa1aab 1.51kB / 1.51kB                                                   0.0s
 => => sha256:8e3ba11ec2a2b39ab372c60c16b421536e50e5ce64a0bc81765c2e38381bcff6 2.21MB / 2.21MB                                                   5.7s
 => => extracting sha256:8e3ba11ec2a2b39ab372c60c16b421536e50e5ce64a0bc81765c2e38381bcff6                                                        1.5s
 => local://context                                                                                                                              0.2s
 => => transferring context: 268B                                                                                                                0.0s
 => /bin/sh -c cat /foo/Dockerfile                                                                                                               0.7s
 => exporting to image                                                                                                                           0.3s
 => => exporting layers                                                                                                                          0.2s
 => => writing image sha256:945871dec9577d28f066f78d93e036aca9905d0977c65b695cbd8acd3384b1cf                                                     0.1s
 => => naming to docker.io/library/hello                                                                                                         0.1s
```
**Dockerfile**
```
img (aws:rean-gov-sd)(kc)$ cat Dockerfile 
# syntax = tonistiigi/dockerfile:runmount20180618
FROM alpine
RUN --mount=target=/foo cat /foo/Dockerfile
img (aws:rean-gov-sd)(kc)$ 
```

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

Fix #136 

@jessfraz @frezbo

### CODE REVIEW

**Comment by frezbo** [comment]
@AkihiroSuda  This looks promising, I never checked the workeropts. Thanks. :100: :+1: 
Let me pull this down and check

**Comment by frezbo** [comment]
@AkihiroSuda This has fixed issue with building normal Dockerfiles :+1: , but the frontend issue still persists.

**Comment by AkihiroSuda** [comment]
added support for gateway

**Comment by frezbo** [comment]
`img` fails to build with the latest commit:

```
# github.com/genuinetools/img/client
client/controller.go:42:26: cannot use gateway.NewGatewayFrontend() (type "github.com/moby/buildkit/frontend".Frontend) as type "github.com/genuinetools/img/vendor/github.com/moby/buildkit/frontend".Frontend in assignment:
	"github.com/moby/buildkit/frontend".Frontend does not implement "github.com/genuinetools/img/vendor/github.com/moby/buildkit/frontend".Frontend (wrong type for Solve method)
		have Solve(context.Context, "github.com/moby/buildkit/frontend".FrontendLLBBridge, map[string]string) ("github.com/moby/buildkit/solver".CachedResult, map[string][]byte, error)
		want Solve(context.Context, "github.com/genuinetools/img/vendor/github.com/moby/buildkit/frontend".FrontendLLBBridge, map[string]string) ("github.com/genuinetools/img/vendor/github.com/moby/buildkit/solver".CachedResult, map[string][]byte, error)
make: *** [Makefile:37: img] Error 2

```

**Comment by frezbo** [comment]
leave it, looks like I did not pull in the changes properly. Sorry for the trouble.

**Comment by jessfraz** [comment]
tjhanks!!!

**Comment by jessfraz** [comment]
I pushed a new release so the builds and image should be available soon :)

**Pull request merged**
