### PR TITLE
add noembed buildtag

### LINKED ISSUE #107: Make the runc binary optional
In distributions (btw. img is now available in gentoo) we usually don't want to bundle binaries but want to specify it as a dependency. Would it be possible to add an option that disables the embedded binary building for runc?

### PR DESCRIPTION
**Pull request by jessfraz**
works like so:
```
$ make install BUILDTAGS="seccomp noembed"
+ install
go install -a -tags "seccomp noembed" -ldflags "-w -X github.com/genuinetools/img/version.GITCOMMIT=455629ae-dirty -X github.com/genuinetools/img/version.VERSION=v0.4.1" .

$ img build -t thing .
FATA[0000] Installing embedded runc binary failed: please install `runc`
```

closes #107

cc @AkihiroSuda

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
WDYT about using CLI flag and/or env var?

**Comment by jessfraz** [comment]
oh yeah we can add that additionally as well, I was mostly thinking the buildtag for the packagers use case

**Comment by jessfraz** [comment]
maybe env var so we don't have another global flag... I just don't know what to call it lol `DISABLE_EMBEDDED_RUNC`

**Comment by AkihiroSuda** [comment]
IMG_DISABLE_EMBEDDED_RUNC?

**Comment by jessfraz** [comment]
ah thats better updating :)

**Pull request merged**
