### PR TITLE
Add platform flag to build

### PR DESCRIPTION
**Pull request by dani909**
Adds the platform flag to build which allows building multiarch images by passing a comma separated list of platforms to it.

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
@tonistiigi PTAL?

**Comment by tonistiigi** [comment]
Using any platform from request as a supported one in the controller seems to counter buildkit design of preventing user from doing wrong things. If the use case for that part is to use qemu(and there is no good other place to put it) then we could do quite a lot with autodetection. Might want to change the flag to stringslice as well (or support both).

**Comment by dani909** [comment]
The intended use case is for qemu and binfmt yes. How would such autodetection be done? I wanted to ask that in the pr message but forgot. Checking all registered formats for binfmt at `/proc/sys/fs/binfmt_misc` is possible on an actual host but not in an container.

**Comment by tonistiigi** [comment]
@dani909 https://github.com/moby/buildkit/pull/840

**Comment by dani909** [comment]
Thanks. Will integrate once merged and released.

**Comment by dani909** [comment]
@AkihiroSuda @tonistiigi PTAL

**Comment by AkihiroSuda** [comment]
looks good, but needs `go mod vendor`

**Comment by dani909** [comment]
now it's vendored

**Comment by jessfraz** [comment]
thanks!!!

**Pull request merged**
