### PR TITLE
add default seccomp profile to containers

### PR DESCRIPTION
**Pull request by jessfraz**

### CODE REVIEW

**Comment by nogoegst** [comment]
@jessfraz it seems that vendor got really big. can you please try adding something like this to `Gopkg.toml` and running`dep ensure` again?
```toml
[prune]
  non-go = true
  unused-packages = true
```
i guess these are mostly unused packages.

**Comment by jessfraz** [comment]
thanks, yeah that was a lot

**Comment by nogoegst** [comment]
omg (+22,986 −5,469) -> (+3,443 −1,924,350) it is like removing Linux 2.2 lol

**Comment by jessfraz** [comment]
that was a really good tip, thanks :)

**Comment by nogoegst** [comment]
Can vendor purging merged separately. It would make this PR reviewable.

**Comment by jessfraz** [comment]
updated :)

**Pull request merged**
